pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hremail__c.field-meta.xml
<CustomField>
    <fullName>hremail__c</fullName>
    <label>hremail</label>
    <type>Email</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrname__c.field-meta.xml
<CustomField>
    <fullName>hrname__c</fullName>
    <label>hrname</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/Mytodaysclass.cls
public class Mytodaysclass 
{
  public static void method1()
  {
      try{
          Hiringmanager__c hr = new Hiringmanager__c();
          hr.hrname__c = 'nareen';
          hr.hremail__c = 'nareen@gmail.com';
          hr.Location__c = 'Hyderabad';
          
          insert hr;
      }
      catch(Exception e)
      {
          system.debug('Message:'+e.getMessage());
          system.debug('Message:'+e.getTypeName());
          system.debug('Message:'+e.getLineNumber());
      }
      	
  }
    
  public static void method2()
  {
      try{
          Hiringmanager__c hr = new Hiringmanager__c();
          hr.hremail__c = 'nareen@gmail.com';
          hr.Location__c = 'Hyderabad';
          
          insert hr;
      }
      catch(Exception e)
      {
          system.debug('Message:'+e.getMessage());
          system.debug('Message:'+e.getTypeName());
          system.debug('Message:'+e.getLineNumber());
      }
      	
  }
    
  public static void method3()
  {
      try{
          List<Integer>mylist = new List<Integer>();
          
          mylist.add(10);
          mylist.add(20);
          mylist.add(30);
          mylist.add(40);
          
          system.debug('Value of mylist:'+mylist);
          system.debug('Value of mylist:'+mylist[0]);
          system.debug('Value of mylist:'+mylist[4]);
      }
      catch(Exception e)
      {
          system.debug('Message:'+e.getMessage());
          system.debug('Message:'+e.getTypeName());
          system.debug('Message:'+e.getLineNumber());
      } 
  }
  public static void method4(integer first,integer second)
  {
      try{
          decimal third = first/second;
          system.debug('Value:'+third);
      }
       catch(Exception e)
      {
          system.debug('Message:'+e.getMessage());
          system.debug('Type of exception:'+e.getTypeName());
          system.debug('Line number:'+e.getLineNumber());
      } 
  }
    
  public static void method5()
  {
      string s;
      boolean b;
      
      try{
          b=s.contains('abc');
          system.debug('s contains data'+b);
      }
      catch(Exception e)
      {
          system.debug('Message:'+e.getMessage());
          system.debug('Type of exception:'+e.getTypeName());
          system.debug('Line number:'+e.getLineNumber());
      } 
  }
}