pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hremail__c.field-meta.xml
<CustomField>
    <fullName>hremail__c</fullName>
    <label>hremail</label>
    <type>Email</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrname__c.field-meta.xml
<CustomField>
    <fullName>hrname__c</fullName>
    <label>hrname</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/Databasehelper2.cls
public class Databasehelper2 
{
   public static void getAllhrrecords()
   {
       Map<Id,Hiringmanager__c>mapHrrecords = new Map<Id,Hiringmanager__c>([select Id,hrname__C,hremail__c,Location__C from Hiringmanager__c]);
       
       system.debug('Record size:'+mapHrrecords.size());
       
       if(!mapHrrecords.isempty())
       {
           for(Hiringmanager__c hr : mapHrrecords.values())
           {
               system.debug('Hiringmanager:'+hr);
           }
       }
   }
}