pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hremail__c.field-meta.xml
<CustomField>
    <fullName>hremail__c</fullName>
    <label>hremail</label>
    <type>Email</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrname__c.field-meta.xml
<CustomField>
    <fullName>hrname__c</fullName>
    <label>hrname</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrphone__c.field-meta.xml
<CustomField>
    <fullName>hrphone__c</fullName>
    <label>hrphone</label>
    <type>Phone</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/CommonHelper.cls
public class CommonHelper 
{
  
   public static void dmloperations()
  {
      User usertobedeactivate = [select id,username,isActive from user where username='cust15@gmail.com' limit 1];
      
      if(usertobedeactivate.id!=null)
      {
          usertobedeactivate.IsActive=false;
          
          update usertobedeactivate;
          
          Createhrrecord();
      }
  }
    
   @future()
   public static void Createhrrecord()
   {
       Hiringmanager__c hr = new Hiringmanager__c();
       
       hr.hrname__c = 'sudeep kumar';
       hr.Location__c = 'Mumbai';
       hr.hremail__c = 'sudeep@gmail.com';
       hr.hrphone__c = '+18393198';
       
       insert hr;
       
       system.debug('hiring manager records:'+hr);
       
   }
}