pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hremail__c.field-meta.xml
<CustomField>
    <fullName>hremail__c</fullName>
    <label>hremail</label>
    <type>Email</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrname__c.field-meta.xml
<CustomField>
    <fullName>hrname__c</fullName>
    <label>hrname</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrphone__c.field-meta.xml
<CustomField>
    <fullName>hrphone__c</fullName>
    <label>hrphone</label>
    <type>Phone</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/HiringManagerUpdateBatch.cls
Global class HiringManagerUpdateBatch implements Database.Batchable<SObject>
{
  Global Database.QueryLocator Start(Database.BatchableContext bContext)
    {
        string hrRecordsQuery = 'Select id,hrname__c, hremail__c,hrphone__c,Location__c from Hiringmanager__c';
        return Database.getQueryLocator(hrRecordsQuery);
    }
    
    Global void Execute(Database.BatchableContext bContext, List<SObject> recordsToProcess)
    {
        if(! recordsToProcess.isEmpty())
        {
            List<Hiringmanager__c> hrRecordsToUpdate = new List<Hiringmanager__c>();
            List<ID> hrRecordsToDelete = new List<ID>();
            
            for(SObject obj : recordsToProcess)
            {
                Hiringmanager__c hrRecord = (Hiringmanager__c) obj;
                
                if(hrRecord.hremail__c != null)
                {
                    hrRecord.Location__c = 'Hyderabad';
                  hrRecord.hrphone__c = '5555888899';
                
                  hrRecordsToUpdate.Add(hrRecord);
                }
                  
            }
            
            if(! hrRecordsToUpdate.isEmpty())
            {
                Update hrRecordsToUpdate;
            }
        }
    }
    
    Global void Finish(Database.BatchableContext bContext)
    {
        System.debug('Batch Job Id is....: '+ bContext.getJobId());
        
        AsyncApexJob jobDetails = [Select id, status, totaljobItems, jobitemsprocessed, 
                                        numberoferrors, createdby.email
                                            from AsyncApexJob
                                                Where id =: bContext.getJobId()];
       system.debug('job details:'+jobDetails); 
        
    }
}