pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrphone__c.field-meta.xml
<CustomField>
    <fullName>hrphone__c</fullName>
    <label>hrphone</label>
    <type>Phone</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/Hiringmanagerextension.cls
public class Hiringmanagerextension
{
   Hiringmanager__c hrRecord;
   
    public Hiringmanagerextension(ApexPages.StandardController controller)
    {
        hrRecord=(Hiringmanager__c)controller.getRecord();
    }
    
    public void ValidateDuplicateHRRecords()
    {
        integer recordsCount = [select count() from Hiringmanager__c where
                               hrphone__c=:hrRecord.hrphone__c];
        
        if(recordsCount>0)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR,'duplicate records found'));
        }
        else
        {
            insert hrRecord;
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.Confirm,'Records inserted successfully'));
        }
    }
}