pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hremail__c.field-meta.xml
<CustomField>
    <fullName>hremail__c</fullName>
    <label>hremail</label>
    <type>Email</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrname__c.field-meta.xml
<CustomField>
    <fullName>hrname__c</fullName>
    <label>hrname</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrphone__c.field-meta.xml
<CustomField>
    <fullName>hrphone__c</fullName>
    <label>hrphone</label>
    <type>Phone</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/HiringManagerUpdateBatchTest.cls
@isTest
public class HiringManagerUpdateBatchTest {
  static testmethod void testhiringmanager()
  {
      createhiringmanager();
      
      //step2
      Test.startTest();
         HiringManagerUpdateBatch pbatch = new HiringManagerUpdateBatch();
         Database.executeBatch(pBatch);
      Test.stopTest();
      
      //step3
      List<Hiringmanager__c>updatedRecords=[select Location__c,hrphone__c,hremail__c from Hiringmanager__c where hremail__c!=null];
      
      //step4
      for(Hiringmanager__c hr : updatedRecords)
      {
          system.assertEquals('Hyderabad',hr.Location__c);
          system.assertEquals('5555888899',hr.hrphone__c);
      }
  }
    
  public static void createhiringmanager()
  {
      List<Hiringmanager__c> lstHrRecords = new List<Hiringmanager__c>();
        
        for(integer counter = 1; counter <= 100; counter++)
        {
            Hiringmanager__c hr = new Hiringmanager__c();
            
            	hr.hrname__c = 'Test - '+ counter;
            	hr.Location__c = 'Mumbai';
            	hr.hremail__c = 'testhr'+counter+'@gmail.com';
            	hr.hrphone__c = '9900665544';
        	    
            lstHrRecords.Add(hr);
        }
        
        if(! lstHrRecords.isEmpty())
        {
            insert lstHrRecords;
        }
  }
}