pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/Hiringmanager__c.object-meta.xml
<CustomObject>
    <label>Hiringmanager</label>
    <nameField>
        <displayFormat>hr-{0000}</displayFormat>
        <label>hrid</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hiringmanagers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hremail__c.field-meta.xml
<CustomField>
    <fullName>hremail__c</fullName>
    <label>hremail</label>
    <type>Email</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrname__c.field-meta.xml
<CustomField>
    <fullName>hrname__c</fullName>
    <label>hrname</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/hrphone__c.field-meta.xml
<CustomField>
    <fullName>hrphone__c</fullName>
    <label>hrphone</label>
    <type>Phone</type>
</CustomField>

pepsicoprojectinfo/force-app/main/default/objects/Hiringmanager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

pepsicoprojectinfo/force-app/main/default/classes/Hiringmanagerutility.cls
public class Hiringmanagerutility 
{
  public static void createhrrecords(string hrname,string hrcity,string hrphone,string hremail)
  {
      Hiringmanager__c hr = new Hiringmanager__c();
      hr.hrname__c = hrname;
      hr.Location__c = hrcity;
      hr.hrphone__c = hrphone;
      hr.hremail__c = hremail;
      
      insert hr;
      
      if(hr.Id !=null)
      {
          system.debug('Hiringmanager record id :'+hr.Id);
          createrelatedposition(hr);
      }
  }
    
  public static void createrelatedposition(Hiringmanager__c hrrecord)
  {
      Position__c pos = new Position__c();
      pos.Position_Name__c = 'sfdc developer';
      pos.Location__c = hrrecord.Location__c;
      pos.Hr_emailid__c = hrrecord.hremail__c;
      pos.Hr_contact_number__c = hrrecord.hrphone__c;
      pos.Hiringmanager__c = hrrecord.Id;
      
      insert pos;
      
      if(pos.Id!=null)
      {
          system.debug('Position id:'+pos.Id);
      }
  }
}